### ISSUE TITLE
segfault when loading 2GB file with read_delim

### ISSUE THREAD

**Issue by stephpeng93** [tidyverse/vroom#449] opened 2022-06-27 23:38 UTC
Hello,
I got a 2020 Mac and am unable to load a file from R code that worked on my 2016 Mac. 

I am able to load a 1 GB file, but anything larger will not load. It’s not a RAM issue either. I’ve tried:
1) uninstalling/reinstalling R Studio and R
2) uninstalling/reinstalling base R packages

Screenshot attached. Any help would be greatly appreciated.
![47032814-E689-4FF4-91D6-D00943FE5733](https://user-images.githubusercontent.com/54967259/176054415-c08c30a0-1e4d-4ade-b6ba-25a8c60dc656.jpeg)

**Comment by jennybc** [comment] 2022-06-28 05:01
Duplicate of https://github.com/tidyverse/readr/issues/1409, which I happened to read first. But I'm closing it in favour of this.

So I repeat:

Is this file available somewhere we can access it?

**Closed** 2022-06-28 05:22 UTC
