### ISSUE TITLE
problem when guessing coltypes if values contains "L" as the last character

### ISSUE THREAD

**Issue by mgacc0** [tidyverse/vroom#476] opened 2022-10-27 16:28 UTC
`vroom:::vroom_` makes a default guess that "28699741L" would mean the number 28699741.

``` r
library(tidyverse)
read_csv('NIF,name
28699741L,Federico')
#> Rows: 1 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (1): name
#> dbl (1): NIF
#> # A tibble: 1 × 2
#>        NIF name    
#>      <dbl> <chr>   
#> 1 28699741 Federico


read_csv('NIF,name
28699741L,Federico',
         col_types = "c")
#> # A tibble: 1 × 2
#>   NIF       name    
#>   <chr>     <chr>   
#> 1 28699741L Federico


read_csv('NIF,name
28699741L,Federico
12345678Z,Fernando
')
#> Rows: 2 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (2): NIF, name
#> # A tibble: 2 × 2
#>   NIF       name    
#>   <chr>     <chr>   
#> 1 28699741L Federico
#> 2 12345678Z Fernando
```

"NIF" is the Spanish identity document:
https://en.wikipedia.org/wiki/Identity_document
https://en.wikipedia.org/wiki/Documento_Nacional_de_Identidad_(Spain)

My opinion is that this should not be the default behavior when guessing coltypes.

**Comment by hadley** [comment] 2023-08-01 12:36
Duplicate of https://github.com/tidyverse/readr/issues/1484

**Closed by hadley** 2023-08-01 12:36 UTC
