### ISSUE TITLE
innecesary quotes when string starts with NA

### ISSUE THREAD

**Issue by mgacc0** [tidyverse/vroom#426] opened 2022-04-10 11:41 UTC
```r
vroom:::vroom_write(
  tibble(col1 = c("JOHN", "NATHAM", "PETER")),
  file = "example.csv"
)
```
produces
```
col1
JOHN
"NATHAM"
PETER
```
but it would be more adequate
```
col1
JOHN
NATHAM
PETER
```
There is no need to quote "NATHAM".
The function `needs_quote` shoud be more sofisticated.
https://github.com/tidyverse/vroom/blob/0e2df4cc8a07fbb007206f6bfcc6a3732e6c4613/src/vroom_write.cc#L78

**Comment by jennybc** [comment] 2022-04-12 15:13
Duplicate of https://github.com/tidyverse/readr/issues/1386

**Comment by mgacc0** [comment] 2022-04-21 22:03
@sbearrows would it be just enough to solve the bug deleting lines 79 to 81 ?https://github.com/tidyverse/vroom/blob/0e2df4cc8a07fbb007206f6bfcc6a3732e6c4613/src/vroom_write.cc#L78
``` c
  if (strncmp(str, na_str, 2) == 0) {
    return true;
  }
```

**Closed** 2022-05-13 22:32 UTC
Labels: bug
